export const LOGIN_EMAIL_REQUEST = 'auth/LOGIN_EMAIL_REQUEST';
export const LOGIN_WITH_FACEBOOK = 'auth/LOGIN_WITH_FACEBOOK';
export const LOGIN_WITH_GOOGLE = 'auth/LOGIN_WITH_GOOGLE';

export const LOGIN_SUCCESS = 'auth/LOGIN_SUCCESS';
export const LOGIN_ERROR = 'auth/LOGIN_ERROR';

export const SIGN_UP_REQUEST = 'auth/SIGN_UP_REQUEST';
export const SIGN_UP_ERROR = 'auth/SIGN_UP_ERROR';

export const LOGOUT = 'auth/LOGOUT';
export const LOGOUT_SUCCESS = 'auth/LOGOUT_SUCCESS';

export const FORGOT_PASSWORD_REQUEST = 'auth/FORGOT_PASSWORD_REQUEST';
export const FORGOT_PASSWORD_SUCCESS = 'auth/FORGOT_PASSWORD_SUCCESS';
export const FORGOT_PASSWORD_ERROR = 'auth/FORGOT_PASSWORD_ERROR';

export const ADD_PERSON_DETAIL_REQUEST = 'auth/ADD_PERSON_DETAIL_REQUEST';
export const ADD_PERSON_DETAIL_SUCCESS = 'auth/ADD_PERSON_DETAIL_SUCCESS';
export const ADD_PERSON_DETAIL_ERROR = 'auth/ADD_PERSON_DETAIL_ERROR';

export const SET_PASSWORD_REQUEST = 'auth/SET_PASSWORD_REQUEST';
export const SET_PASSWORD_SUCCESS = 'auth/SET_PASSWORD_SUCCESS';
export const SET_PASSWORD_ERROR = 'auth/SET_PASSWORD_ERROR';
